name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "FL Studio 20.7.2.1863"
  comment: "Image Line Fruity Loops Studio 20.7.2.1863"
  url: "http://demodownload.image-line.com/flstudio/flstudio_win_20.7.2.1863.exe"
  file_name: "flstudio_win_20.7.2.1863.exe"
  piece_size: 24 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
